version: '3.8'
services:
  app:
    build:
      context: .
    container_name: gestor_app
    volumes:
      - ./backend:/app/backend
    expose:
      - 8000

  nginx:
    image: nginx:latest
    container_name: gestor_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/react-app/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - app
