version: '3.89
services:
  backend:
    build: .
    context: ./backend
    container_name: gestor_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    expose:
      - 8000

  frontend:
    build: .
      context: ./frontend/react-app
    container_name: gestor_frontend
    command: npm run build
    volumes:
      - ./frontend/react-app:/app
  nginx:
    image: nginx:latest
    container_name: gestor_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/react-app/build:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
